sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "7"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_install:
  - npm install -g npm@5

script:
  - if [ -n "DANGER_GITHUB_API_TOKEN" ]; then echo {} > ./.babelrc && npx danger; fi
  - ng lint
  - ng test --single-run --code-coverage
  - ng build --prod
  - ng e2e

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - ng build --prod
  - ls -l
  - cd dist
  - echo "rxjsdocs.com" >> CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: dist
  on:
    branch: master
