sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "7"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_install:
  - npm install -g npm@5

script:
  - if [ -n "DANGER_GITHUB_API_TOKEN" ]; then echo {} > ./.babelrc && npx danger; fi
  - ng lint
  - ng test --single-run --code-coverage
  - ng build --prod
  - ng e2e

before_deploy:
  - rm -rf ./dist
  - ng build
  - yes | rm *.* && rm -rf ./e2e ./node_modules ./src
  - cp -r ./dist/* ./

deploy:
  provider: azure_web_apps
  verbose: true
  skip_cleanup: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
